/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import threads.ZalogujSieThread;

/**
 *
 * @author pikak
 */
public class LogowanieView extends javax.swing.JFrame {

    /**
     * Creates new form logowanieView
     */
    public LogowanieView() {
        initComponents();
        zalogujButton.addActionListener(new ZalogujSieThread(errorText, loginTextField, hasloTextField));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        zalogujButton = new javax.swing.JToggleButton();
        loginTextField = new javax.swing.JTextField();
        errorText = new javax.swing.JLabel();
        konfiguracjaButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        hasloTextField = new javax.swing.JPasswordField();
        jMenuBar1 = new javax.swing.JMenuBar();
        ZamknijJMenu = new javax.swing.JMenu();
        KonfiguracjaJMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));

        zalogujButton.setFont(new java.awt.Font("Geologica", 1, 24)); // NOI18N
        zalogujButton.setText("Zaloguj");
        zalogujButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zalogujButtonActionPerformed(evt);
            }
        });

        loginTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginTextFieldActionPerformed(evt);
            }
        });

        errorText.setFont(new java.awt.Font("Geologica", 1, 18)); // NOI18N
        errorText.setForeground(new java.awt.Color(255, 0, 51));
        errorText.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                errorTextPropertyChange(evt);
            }
        });

        konfiguracjaButton.setFont(new java.awt.Font("Geologica", 1, 18)); // NOI18N
        konfiguracjaButton.setText("Konfiguracja połączenia");
        konfiguracjaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                konfiguracjaButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Geologica", 1, 36)); // NOI18N
        jLabel4.setText("Zaloguj się");

        jLabel5.setFont(new java.awt.Font("Geologica", 1, 36)); // NOI18N
        jLabel5.setText("Hasło: ");

        jLabel6.setFont(new java.awt.Font("Geologica", 1, 36)); // NOI18N
        jLabel6.setText("Login:");

        jLabel1.setText("2023 - Krzysztof Jankowski ");

        jLabel8.setFont(new java.awt.Font("Geologica", 1, 36)); // NOI18N
        jLabel8.setText("Witaj!");

        hasloTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasloTextFieldActionPerformed(evt);
            }
        });

        ZamknijJMenu.setText("Zamknij");
        ZamknijJMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ZamknijJMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(ZamknijJMenu);

        KonfiguracjaJMenu.setText("Konfiguracja");
        KonfiguracjaJMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KonfiguracjaJMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(KonfiguracjaJMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(errorText, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                .addGap(184, 184, 184))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(463, 463, 463))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(konfiguracjaButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                                        .addComponent(zalogujButton, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(31, 31, 31))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(18, 18, 18)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(loginTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                                            .addComponent(hasloTextField)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(errorText, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(93, 93, 93)
                .addComponent(jLabel4)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(loginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(hasloTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zalogujButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(konfiguracjaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void konfiguracjaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konfiguracjaButtonActionPerformed
        var oknoKonfiguracji = new KonfiguracjaView();
        oknoKonfiguracji.setLocation(this.getLocation().x, this.getLocation().y);
        oknoKonfiguracji.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_konfiguracjaButtonActionPerformed

    private void ZamknijJMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ZamknijJMenuMouseClicked
        this.dispose();
    }//GEN-LAST:event_ZamknijJMenuMouseClicked

    private void KonfiguracjaJMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KonfiguracjaJMenuMouseClicked
        var oknoKonfiguracji = new KonfiguracjaView();
        oknoKonfiguracji.setLocation(this.getLocation().x, this.getLocation().y);
        oknoKonfiguracji.setVisible(true);

        this.dispose();    }//GEN-LAST:event_KonfiguracjaJMenuMouseClicked

    private void hasloTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasloTextFieldActionPerformed
        hasloTextField.setText("");
    }//GEN-LAST:event_hasloTextFieldActionPerformed

    private void loginTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginTextFieldActionPerformed
        loginTextField.setText("");
    }//GEN-LAST:event_loginTextFieldActionPerformed

    private void zalogujButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zalogujButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zalogujButtonActionPerformed

    private void errorTextPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_errorTextPropertyChange
        if (errorText.getText().contains("Witaj")) {
            this.setVisible(false);
        }
    }//GEN-LAST:event_errorTextPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogowanieView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogowanieView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogowanieView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogowanieView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogowanieView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu KonfiguracjaJMenu;
    private javax.swing.JMenu ZamknijJMenu;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel errorText;
    private javax.swing.JPasswordField hasloTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton konfiguracjaButton;
    private javax.swing.JTextField loginTextField;
    private javax.swing.JToggleButton zalogujButton;
    // End of variables declaration//GEN-END:variables
}
